=== ruhulmath08/IDB-J2EE-Round-33/XML Design/XMLclass_2_05_11_2017/src/StudentInfo/StudentInformation.dtd
<?xml version='1.0' encoding='UTF-8'?>

<!--
    TODO define vocabulary identification
    PUBLIC ID: -//vendor//vocabulary//EN
    SYSTEM ID: http://server/path/StudentInformation.dtd

-->

<!--
    An example how to use this DTD from your XML document:

    <?xml version="1.0"?>

    <!DOCTYPE students SYSTEM "StudentInformation.dtd">

    <students>
    ...
    </students>
-->

<!--- Put your DTDDoc comment here. -->
<!ELEMENT students (student)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT student (id|name|age|email)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT id (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT name (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT age (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT email (#PCDATA)>

=== ruhulmath08/IDB-J2EE-Round-33/XML Design/XMLclass_2_05_11_2017/src/StudentInfo/StudentInformation.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE students SYSTEM "StudentInformation.dtd">
<students>
    <student>
        <id>10001</id>
        <name>Ruhul</name>
        <age>29</age>
        <email>ruhulmath08@gmail.com</email>
    </student>
    
    <student>
        <id>10002</id>
        <name>Reza</name>
        <age>30</age>
        <email>rezaGdesiger@gmail.com</email>
    </student>
</students>
